### ISSUE TITLE
Chiselling Table doesn't inform the player when their chisel isn't a high enough level

### ISSUE THREAD

**Issue by ghost** [LordDeatHunter/Smithee#4]
MC Version: 1.16.4
Fabric Version 0.10.8
Smithee Version: 0.1.4

I notice that materials cannot be chiselled by chisels of a lower mining level than the material. However, I only figured this out through trial and error. It would be greatly useful if there was some indication in the Chiselling Table UI that the player needed a higher tier of chisel to create the desired part.

Preferably, the cost shouldn't display if the part cannot be chiselled due to the above restriction, as it misleads the player into thinking they can make the part.

**Comment by LordDeatHunter** [comment]
Done 👍
