### ISSUE TITLE
Tool mining levels

### ISSUE THREAD

**Issue by Danklor** [LordDeatHunter/Smithee#8]
I assembled two iron picks, but both have a mining level of 0 instead of the expected mining level of 2. The first had a wooden handle and wooden binding. The second had a wooden handle and an iron binding.

**Comment by Danklor** [comment]
Both versions 0.1.5 and 0.2.2a are affected in MC 1.16.4 with Fabric Loader 0.11.1 and Fabric API 0.29.3+1.16.

**Comment by LordDeatHunter** [comment]
I think that's a display issue. Did you try mining?

**Comment by Danklor** [comment]
I just rechecked mining iron ore. The ore breaks at the expected speed for an iron pick, but no iron ore item drops.

**Comment by Danklor** [comment]
Oops! User error! I did not notice that due to the iron pick's Magnetic attribute that the mined ores were moving directly to my inventory without dropping in the world. After retesting and observing my inventory I see that the iron pick is indeed working as intended.
Sorry for the wild goose chase.
